//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big library detected.
        /// </summary>
        internal static string MsgBigLibraryCaption {
            get {
                return ResourceManager.GetString("MsgBigLibraryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This library is pretty big (more than 4 MB) for an standard Arduino library size.
        ///
        ///Are you sure you want to add this library?.
        /// </summary>
        internal static string MsgBigLibraryText {
            get {
                return ResourceManager.GetString("MsgBigLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add the selected library.
        /// </summary>
        internal static string MsgErrorAddingLibraryText {
            get {
                return ResourceManager.GetString("MsgErrorAddingLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgErrorCaption {
            get {
                return ResourceManager.GetString("MsgErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library can&apos;t be updated for some reason and it will not be added for now. Check if the files are accesable and try again.
        ///
        ///If the problem continues, check if the library works without any fix or check the library author&apos;s website to get a newer version..
        /// </summary>
        internal static string MsgErrorFixingLibraryText {
            get {
                return ResourceManager.GetString("MsgErrorFixingLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the right files inside the library, check the library and try again.
        /// </summary>
        internal static string MsgErrorInvalidLibraryText {
            get {
                return ResourceManager.GetString("MsgErrorInvalidLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible old library detected.
        /// </summary>
        internal static string MsgOldLibraryCaption {
            get {
                return ResourceManager.GetString("MsgOldLibraryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This library seems to be outdated for the current Arduino IDE. Problems found:
        ///{0}
        ///
        ///Should this application attempt to fix these issues automatically?.
        /// </summary>
        internal static string MsgOldLibraryText {
            get {
                return ResourceManager.GetString("MsgOldLibraryText", resourceCulture);
            }
        }
    }
}
